name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - name: Install CompatHelper
        shell: julia --startup-file=no --color=yes {0}
        run: |
          using Pkg
          Pkg.activate(joinpath(ENV["RUNNER_TEMP"], "compathelper"))
          Pkg.add(PackageSpec(name="CompatHelper", version="3"))
      - name: Run CompatHelper
        shell: julia --startup-file=no --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          using Pkg
          Pkg.activate(joinpath(ENV["RUNNER_TEMP"], "compathelper"))
          using CompatHelper
          CompatHelper.main()
